defmodule Wotex.Workspace.Catalogue do
  @moduledoc """
  The family catalogue, `docs/catalogue.yaml`, rendered from every package's
  `docs/packages/<name>/specs/catalogue.yaml`.

  Each package catalogue contributes its `package` and its `specifications`
  (`id`, `version`, `path`, `implementation_status`). Paths are resolved with
  the convention from `docs/README.md`, "Catalogue paths": a path starting
  with `docs/` is relative to `docs/packages/<name>/`, any other path is
  relative to `packages/<name>/`. The rendering is deterministic: packages
  sorted by name, specifications sorted by id, every scalar quoted.
  """

  alias Wotex.Workspace
  alias Wotex.Workspace.Manifest

  @schema_version "1.0.0"
  @generated_from "tooling/check/catalogue"
  @output "docs/catalogue.yaml"
  @statuses ~w(planned partial implemented deprecated withdrawn)

  @type specification :: %{
          id: String.t(),
          version: String.t(),
          implementation_status: String.t(),
          path: Path.t()
        }

  @type entry :: %{
          name: String.t(),
          app: String.t(),
          catalogue: Path.t(),
          specifications: [specification()]
        }

  @type problem :: {String.t(), String.t()}

  @doc "Repository-relative path of the rendered family catalogue."
  @spec output() :: Path.t()
  def output, do: @output

  @doc "Repository-relative path of a package's catalogue."
  @spec catalogue_path(String.t()) :: Path.t()
  def catalogue_path(name), do: "docs/packages/#{name}/specs/catalogue.yaml"

  @doc """
  Loads every package catalogue below `root`.

  Returns the entries plus the list of resolved specification paths that do
  not exist (`{package, message}`). Structural errors (unreadable YAML,
  missing or malformed fields) fail the load.
  """
  @spec load(Manifest.t(), Path.t()) :: {:ok, [entry()], [problem()]} | {:error, String.t()}
  def load(%Manifest{} = manifest \\ Manifest.load!(), root \\ Workspace.root()) do
    result =
      manifest
      |> Manifest.packages()
      |> Enum.reduce_while({:ok, [], []}, fn package, {:ok, entries, problems} ->
        case load_package(package, root) do
          {:ok, entry, missing} -> {:cont, {:ok, [entry | entries], problems ++ missing}}
          {:error, message} -> {:halt, {:error, message}}
        end
      end)

    case result do
      {:ok, entries, problems} -> {:ok, Enum.reverse(entries), problems}
      {:error, message} -> {:error, message}
    end
  end

  @doc "Renders entries as the family catalogue YAML document."
  @spec render([entry()]) :: String.t()
  def render(entries) do
    packages =
      entries
      |> Enum.sort_by(& &1.name)
      |> Enum.map_join(&render_package/1)

    """
    # Generated by `mix wotex.catalogue`; do not edit. Each package's
    # docs/packages/<name>/specs/catalogue.yaml owns the values below.
    schema_version: #{quote_scalar(@schema_version)}
    generated_from: #{@generated_from}
    packages:
    """ <> packages
  end

  @doc """
  Loads, renders and writes `docs/catalogue.yaml`. Returns the number of
  specifications and the unresolved-path problems.
  """
  @spec write(Manifest.t(), Path.t()) ::
          {:ok, non_neg_integer(), [problem()]} | {:error, String.t()}
  def write(%Manifest{} = manifest \\ Manifest.load!(), root \\ Workspace.root()) do
    with {:ok, entries, problems} <- load(manifest, root) do
      File.write!(Path.join(root, @output), render(entries))
      {:ok, count(entries), problems}
    end
  end

  @doc """
  Fails when the committed `docs/catalogue.yaml` differs from the rendering
  or when any specification path does not resolve.
  """
  @spec check(Manifest.t(), Path.t()) :: :ok | {:error, String.t()}
  def check(%Manifest{} = manifest \\ Manifest.load!(), root \\ Workspace.root()) do
    with {:ok, entries, problems} <- load(manifest, root),
         :ok <- no_problems(problems) do
      expected = render(entries)
      path = Path.join(root, @output)

      case File.read(path) do
        {:ok, ^expected} -> :ok
        {:ok, _} -> {:error, "#{@output} is stale; run `mix wotex.catalogue`"}
        {:error, reason} -> {:error, "#{@output}: #{:file.format_error(reason)}"}
      end
    end
  end

  @doc "The total number of specifications across entries."
  @spec count([entry()]) :: non_neg_integer()
  def count(entries), do: Enum.sum_by(entries, &length(&1.specifications))

  @doc """
  Resolves a catalogue path to a repository-relative path.
  """
  @spec resolve_path(String.t(), String.t()) :: Path.t()
  def resolve_path(name, "docs/" <> rest), do: "docs/packages/#{name}/#{rest}"
  def resolve_path(name, path), do: "packages/#{name}/#{path}"

  @doc """
  Validates a decoded package catalogue (string keys) for package `name`
  with OTP application `app` and returns its entry.
  """
  @spec parse(String.t(), String.t(), term()) :: {:ok, entry()} | {:error, String.t()}
  def parse(name, app, %{"package" => package, "specifications" => specifications} = _)
      when is_list(specifications) do
    with :ok <- check_package_field(name, app, package),
         {:ok, parsed} <- parse_specifications(name, specifications) do
      {:ok,
       %{
         name: name,
         app: app,
         catalogue: catalogue_path(name),
         specifications: Enum.sort_by(parsed, & &1.id)
       }}
    end
  end

  def parse(name, _, map) when is_map(map),
    do: {:error, "#{catalogue_path(name)}: package and specifications are required"}

  def parse(name, _, _), do: {:error, "#{catalogue_path(name)}: must be a mapping"}

  defp load_package(package, root) do
    relative = catalogue_path(package.name)
    absolute = Path.join(root, relative)

    with {:ok, map} <- read_yaml(absolute, relative),
         {:ok, entry} <- parse(package.name, package.app, map) do
      {:ok, entry, missing_paths(entry, root)}
    end
  end

  defp read_yaml(absolute, relative) do
    if File.regular?(absolute) do
      case YamlElixir.read_from_file(absolute) do
        {:ok, map} -> {:ok, map}
        {:error, error} -> {:error, "#{relative}: #{Exception.message(error)}"}
      end
    else
      {:error, "#{relative}: missing"}
    end
  end

  defp check_package_field(name, app, package) when package in [name, app], do: :ok

  defp check_package_field(name, app, package),
    do:
      {:error,
       "#{catalogue_path(name)}: package #{inspect(package)} is neither #{inspect(name)} " <>
         "nor #{inspect(app)}"}

  defp parse_specifications(name, specifications) do
    result =
      specifications
      |> Enum.with_index()
      |> Enum.reduce_while({:ok, []}, fn {spec, index}, {:ok, acc} ->
        case parse_specification(name, index, spec) do
          {:ok, parsed} -> {:cont, {:ok, [parsed | acc]}}
          {:error, message} -> {:halt, {:error, message}}
        end
      end)

    case result do
      {:ok, parsed} -> check_unique_ids(name, Enum.reverse(parsed))
      {:error, message} -> {:error, message}
    end
  end

  defp parse_specification(name, index, spec) when is_map(spec) do
    fields = ~w(id version path implementation_status)

    with {:ok, values} <- required_strings(name, index, spec, fields),
         :ok <- check_status(name, values["id"], values["implementation_status"]) do
      {:ok,
       %{
         id: values["id"],
         version: values["version"],
         implementation_status: values["implementation_status"],
         path: resolve_path(name, values["path"])
       }}
    end
  end

  defp parse_specification(name, index, _),
    do: {:error, "#{catalogue_path(name)}: specifications[#{index}] must be a mapping"}

  defp required_strings(name, index, spec, fields) do
    Enum.reduce_while(fields, {:ok, %{}}, fn field, {:ok, acc} ->
      case Map.get(spec, field) do
        value when is_binary(value) and value != "" ->
          {:cont, {:ok, Map.put(acc, field, value)}}

        _ ->
          {:halt,
           {:error,
            "#{catalogue_path(name)}: specifications[#{index}].#{field} must be a non-empty string"}}
      end
    end)
  end

  defp check_status(_, _, status) when status in @statuses, do: :ok

  defp check_status(name, id, status),
    do:
      {:error,
       "#{catalogue_path(name)}: #{id} has implementation_status #{inspect(status)}; " <>
         "expected one of #{Enum.join(@statuses, ", ")}"}

  defp check_unique_ids(name, parsed) do
    duplicates =
      parsed
      |> Enum.frequencies_by(& &1.id)
      |> Enum.filter(fn {_, n} -> n > 1 end)
      |> Enum.map(&elem(&1, 0))
      |> Enum.sort()

    case duplicates do
      [] ->
        {:ok, parsed}

      ids ->
        {:error, "#{catalogue_path(name)}: duplicate specification ids #{Enum.join(ids, ", ")}"}
    end
  end

  defp missing_paths(entry, root) do
    for spec <- entry.specifications,
        not File.exists?(Path.join(root, spec.path)),
        do: {entry.name, "#{entry.catalogue}: #{spec.id} path #{spec.path} does not exist"}
  end

  defp no_problems([]), do: :ok

  defp no_problems(problems),
    do: {:error, problems |> Enum.map_join("\n", &elem(&1, 1))}

  defp render_package(entry) do
    specs =
      case entry.specifications do
        [] -> "    specifications: []\n"
        specs -> "    specifications:\n" <> Enum.map_join(specs, &render_specification/1)
      end

    """
      #{entry.name}:
        app: #{quote_scalar(entry.app)}
        catalogue: #{quote_scalar(entry.catalogue)}
    """ <> specs
  end

  defp render_specification(spec) do
    """
          - id: #{quote_scalar(spec.id)}
            version: #{quote_scalar(spec.version)}
            implementation_status: #{quote_scalar(spec.implementation_status)}
            path: #{quote_scalar(spec.path)}
    """
  end

  # JSON string syntax is valid YAML double-quoted scalar syntax.
  defp quote_scalar(value) when is_binary(value), do: JSON.encode!(value)
end
