Code.require_file("support/serial_peer.ex", __DIR__)
Code.require_file("support/fake_uart.ex", __DIR__)
Code.require_file("support/controlled_serial.ex", __DIR__)
Code.require_file("support/startup_serial.ex", __DIR__)
ExUnit.start()
