Code.require_file("support/serial_peer.ex", __DIR__)
Code.require_file("support/fake_uart.ex", __DIR__)
Code.require_file("support/controlled_serial.ex", __DIR__)
Code.require_file("support/startup_serial.ex", __DIR__)
Code.require_file("support/binding_serial.ex", __DIR__)
Code.require_file("support/credentials.ex", __DIR__)
Code.require_file("support/permit_serial.ex", __DIR__)
Code.require_file("support/migration_serial.ex", __DIR__)
Code.require_file("support/key_credentials.ex", __DIR__)
Code.require_file("support/key_serial.ex", __DIR__)
ExUnit.start()
