defmodule Wotex.Workspace.CatalogueTest do
  @moduledoc false

  use ExUnit.Case, async: true

  alias Wotex.Workspace.Catalogue
  alias Wotex.Workspace.Manifest
  alias WotexWorkspace.Fixtures

  @manifest_map %{
    "packages" => %{
      "alpha" => %{"app" => "alpha", "depends_on" => []},
      "beta" => %{"app" => "wotex_beta", "depends_on" => ["alpha"]}
    }
  }

  @alpha """
  schema_version: "1.2.0"
  package: "alpha"
  completion_plan: "docs/plans/alpha-completion.md"
  specifications:
    - id: "ALP.02"
      version: "1.0.0"
      path: "priv/fixtures/contract-v1.json"
      implementation_status: partial
      standards: []
    - id: "ALP.01"
      version: "1.1.0"
      path: "docs/specs/ALP.01-values.md"
      implementation_status: "implemented"
  """

  @beta """
  schema_version: "1.1.0"
  package: wotex_beta
  specifications: []
  """

  setup context do
    root = Fixtures.tmp_dir(context)
    {:ok, manifest} = Manifest.from_map(@manifest_map)
    Fixtures.write!(root, "docs/packages/alpha/specs/catalogue.yaml", @alpha)
    Fixtures.write!(root, "docs/packages/alpha/specs/ALP.01-values.md", "# ALP.01\n")
    Fixtures.write!(root, "packages/alpha/priv/fixtures/contract-v1.json", "{}\n")
    Fixtures.write!(root, "docs/packages/beta/specs/catalogue.yaml", @beta)
    File.mkdir_p!(Path.join(root, "docs"))
    %{root: root, manifest: manifest}
  end

  @expected """
  # Generated by `mix wotex.catalogue`; do not edit. Each package's
  # docs/packages/<name>/specs/catalogue.yaml owns the values below.
  schema_version: "1.0.0"
  generated_from: tooling/check/catalogue
  packages:
    alpha:
      app: "alpha"
      catalogue: "docs/packages/alpha/specs/catalogue.yaml"
      specifications:
        - id: "ALP.01"
          version: "1.1.0"
          implementation_status: "implemented"
          path: "docs/packages/alpha/specs/ALP.01-values.md"
        - id: "ALP.02"
          version: "1.0.0"
          implementation_status: "partial"
          path: "packages/alpha/priv/fixtures/contract-v1.json"
    beta:
      app: "wotex_beta"
      catalogue: "docs/packages/beta/specs/catalogue.yaml"
      specifications: []
  """

  test "renders a deterministic family catalogue", %{root: root, manifest: manifest} do
    assert {:ok, entries, []} = Catalogue.load(manifest, root)
    assert Catalogue.render(entries) == @expected
    assert Catalogue.count(entries) == 2

    # Rendering is independent of input order.
    assert Catalogue.render(Enum.reverse(entries)) == @expected
  end

  test "the rendering is valid YAML that round-trips", %{root: root, manifest: manifest} do
    assert {:ok, entries, []} = Catalogue.load(manifest, root)
    assert {:ok, decoded} = YamlElixir.read_from_string(Catalogue.render(entries))
    assert decoded["schema_version"] == "1.0.0"
    assert decoded["generated_from"] == "tooling/check/catalogue"
    assert Map.keys(decoded["packages"]) == ["alpha", "beta"]

    assert [%{"id" => "ALP.01"}, %{"id" => "ALP.02"}] =
             decoded["packages"]["alpha"]["specifications"]
  end

  test "write/2 and check/2 agree", %{root: root, manifest: manifest} do
    assert {:error, message} = Catalogue.check(manifest, root)
    assert message =~ "docs/catalogue.yaml"

    assert {:ok, 2, []} = Catalogue.write(manifest, root)
    assert File.read!(Path.join(root, "docs/catalogue.yaml")) == @expected
    assert Catalogue.check(manifest, root) == :ok

    File.write!(Path.join(root, "docs/catalogue.yaml"), @expected <> "# edited\n")
    assert {:error, message} = Catalogue.check(manifest, root)
    assert message =~ "stale"
  end

  test "resolves docs/ paths to the documentation tree and others to the package" do
    assert Catalogue.resolve_path("alpha", "docs/specs/X.md") == "docs/packages/alpha/specs/X.md"
    assert Catalogue.resolve_path("alpha", "priv/x.json") == "packages/alpha/priv/x.json"
    assert Catalogue.resolve_path("alpha", "bin/check.exs") == "packages/alpha/bin/check.exs"
  end

  test "reports specification paths that do not exist", %{root: root, manifest: manifest} do
    File.rm!(Path.join(root, "packages/alpha/priv/fixtures/contract-v1.json"))

    assert {:ok, _entries, [{"alpha", message}]} = Catalogue.load(manifest, root)
    assert message =~ "ALP.02 path packages/alpha/priv/fixtures/contract-v1.json does not exist"

    assert {:ok, 2, [_problem]} = Catalogue.write(manifest, root)
    assert {:error, message} = Catalogue.check(manifest, root)
    assert message =~ "does not exist"
  end

  test "rejects a missing catalogue, bad fields and a foreign package name", %{
    root: root,
    manifest: manifest
  } do
    File.rm!(Path.join(root, "docs/packages/beta/specs/catalogue.yaml"))

    assert {:error, "docs/packages/beta/specs/catalogue.yaml: missing"} =
             Catalogue.load(manifest, root)

    assert {:error, message} =
             Catalogue.parse("beta", "wotex_beta", %{"package" => "gamma", "specifications" => []})

    assert message =~ ~s(package "gamma" is neither "beta" nor "wotex_beta")

    assert {:ok, _entry} =
             Catalogue.parse("beta", "wotex_beta", %{"package" => "beta", "specifications" => []})

    assert {:error, message} =
             Catalogue.parse("beta", "wotex_beta", %{
               "package" => "wotex_beta",
               "specifications" => [%{"id" => "B.1", "version" => "1.0.0", "path" => "docs/x.md"}]
             })

    assert message =~ "specifications[0].implementation_status must be a non-empty string"

    assert {:error, message} =
             Catalogue.parse("beta", "wotex_beta", %{
               "package" => "wotex_beta",
               "specifications" => [
                 %{
                   "id" => "B.1",
                   "version" => "1.0.0",
                   "path" => "docs/x.md",
                   "implementation_status" => "done"
                 }
               ]
             })

    assert message =~ ~s(B.1 has implementation_status "done")

    spec = %{
      "id" => "B.1",
      "version" => "1.0.0",
      "path" => "docs/x.md",
      "implementation_status" => "planned"
    }

    assert {:error, message} =
             Catalogue.parse("beta", "wotex_beta", %{
               "package" => "wotex_beta",
               "specifications" => [spec, spec]
             })

    assert message =~ "duplicate specification ids B.1"

    assert {:error, message} = Catalogue.parse("beta", "wotex_beta", %{"package" => "beta"})
    assert message =~ "package and specifications are required"
    assert {:error, message} = Catalogue.parse("beta", "wotex_beta", [])
    assert message =~ "must be a mapping"
  end
end
