ExUnit.start(exclude: [:interop, :hardware])
Code.require_file("support/client.ex", __DIR__)
Code.require_file("support/runtime_error_port.ex", __DIR__)
Code.require_file("support/runtime_client.ex", __DIR__)
Code.require_file("support/runtime_recording_transport.ex", __DIR__)
Code.require_file("support/native_fixture.ex", __DIR__)
